---
language: nix
env:
  global:
    - STORE=$HOME/nix-store
  matrix:
    - PYMKS_USE_FFTW=1
cache:
  directories:
    - $STORE
before_install:
  - sudo mkdir -p /etc/nix
  - echo "binary-caches = https://cache.nixos.org/ file://$STORE" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $STORE
  - nix copy --to file://$STORE -f shell.nix buildInputs
script:
  - nix-shell --command "py.test"
