---
language: nix
env:
  global:
    - STORE=$HOME/nix-store
cache:
  directories:
    - $STORE
before_install:
  - sudo mkdir -p /etc/nix
  - echo "binary-caches = https://cache.nixos.org/ file://$STORE" | sudo tee -a /etc/nix/nix.conf > /dev/null
  - echo 'require-sigs = false' | sudo tee -a /etc/nix/nix.conf > /dev/null
before_cache:
  - mkdir -p $STORE
  - nix copy --to file://$STORE -f shell.nix buildInputs
install:
  - nix-build -A buildInputs
script:
  - nix-shell --pure --command "export PYMKS_USE_FFTW=1; py.test"
  - nix-shell --pure --command "export PYMKS_USE_FFTW=0; py.test"
  - nix-shell --pure --command "pylint --rcfile=.pylintrc pymks/fmks pymks/fmks/tests"
  - nix-shell --pure --command "flake8 pymks/fmks pymkgs/fmks/tests"
  - nix-shell --pure -p "python36Packages.black" --command "black --check pymks/fmks pymks/fmks/tests"
