---
language: python
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -y -n test-environment python=3.5
  - source activate test-environment
  - conda install -q -y -n test-environment numpy scipy pytest scikit-learn matplotlib pytest-cov
  - conda install -q -y -n test-environment sympy cython pytables jupyter
  - conda install -q -y -n test-environment -c conda-forge pyfftw
  - conda install -q -y -n test-environment -c conda-forge sfepy=2017.2
  - pip install pylint nbval
  - unset VIRTUAL_ENV
  - pip install .
script:
  - py.test
  - pylint --extension-pkg-whitelist=numpy fmks
