{% set name = "pymks" %}
{% set version = "0.3.3.dev59+g0ca00e2" %}
{% set github_org = "wd15" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/{{ github_org }}/{{ name }}.git
  git_rev: 0ca00e2

build:
  number: 5
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python

  run:
    - python
    - numpy
    - scipy
    - scikit-learn
    - pytest
    - pytest-cov
    - nbval
    - sfepy

about:
  home: http://{{ name }}.org
