{% set name = "pymks" %}
{% set version = load_setup_py_data().version %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/materialsinnovation/{{ name }}.git
  git_rev: 817dc61

build:
  number: 1

requirements:
  build:
    - python
    - anaconda
    - pytest
    - scikit-learn
    - pytest-cov
    - pylint
    - cython
    - sympy
    - pytables

  run:
    - python
    - anaconda
    - pytest
    - scikit-learn
    - pytest-cov
    - pylint
    - cython
    - sympy
    - pytables
    - pyparsing
    - matplotlib

about:
  home: http://{{ name }}.org
